stage: ${env.STAGE}
distributionId: ${env.DISTRIBUTION_ID}

minery-landing-frontend:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    bucketName: "minery-landing-frontend-${stage}"
    bucketRegion: ap-northeast-2
    name:
      defaultLambda: "minery-landing-frontend-${stage}"
    roleArn: arn:aws:iam::917306879000:role/8m1ef18-etyjhsc
    build:
      env:
        STAGE: "${stage}"
    cloudfront:
      distributionId: E1P6MR7TPU58M1
      comment: "minery-landing-frontend-${stage}"
